// <auto-generated />
using System;
using AdressverwaltungApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdressverwaltungApi.Migrations
{
    [DbContext(typeof(AdresseDbContext))]
    partial class AdresseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // === Adresse ===
            modelBuilder.Entity("AdressverwaltungApi.Models.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("Ort").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("Plz").IsRequired().HasMaxLength(10).HasColumnType("character varying(10)");
                    b.Property<string>("Strasse").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Strassennummer").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<string>("Vorname").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    // Audit-Felder
                    b.Property<DateTime>("CreateDate").IsRequired().HasColumnType("timestamp without time zone");
                    b.Property<string>("CreatedBy").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime?>("ChangeDate").HasColumnType("timestamp without time zone");
                    b.Property<string>("ChangedBy").HasMaxLength(100).HasColumnType("character varying(100)");
                    // Gültigkeitszeitraum
                    b.Property<DateOnly>("DateFrom").IsRequired().HasColumnType("date");
                    b.Property<DateOnly?>("DateTo").HasColumnType("date");
                    b.HasKey("Id");
                    b.ToTable("Adressen");
                });

            // === City ===
            modelBuilder.Entity("AdressverwaltungApi.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("PostalCode").IsRequired().HasMaxLength(10).HasColumnType("character varying(10)");
                    b.Property<string>("CityName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    // Audit-Felder
                    b.Property<DateTime>("CreateDate").IsRequired().HasColumnType("timestamp without time zone");
                    b.Property<string>("CreatedBy").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime?>("ChangeDate").HasColumnType("timestamp without time zone");
                    b.Property<string>("ChangedBy").HasMaxLength(100).HasColumnType("character varying(100)");
                    // Gültigkeitszeitraum
                    b.Property<DateOnly>("DateFrom").IsRequired().HasColumnType("date");
                    b.Property<DateOnly?>("DateTo").HasColumnType("date");
                    b.HasKey("Id");
                    b.HasIndex("PostalCode");
                    b.ToTable("Cities");
                });

            // === User ===
            modelBuilder.Entity("AdressverwaltungApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                    b.Property<string>("DisplayName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    // Audit-Felder
                    b.Property<DateTime>("CreateDate").IsRequired().HasColumnType("timestamp without time zone");
                    b.Property<string>("CreatedBy").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime?>("ChangeDate").HasColumnType("timestamp without time zone");
                    b.Property<string>("ChangedBy").HasMaxLength(100).HasColumnType("character varying(100)");
                    // Gültigkeitszeitraum
                    b.Property<DateOnly>("DateFrom").IsRequired().HasColumnType("date");
                    b.Property<DateOnly?>("DateTo").HasColumnType("date");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Users");
                });

            // === Settings ===
            modelBuilder.Entity("AdressverwaltungApi.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("NotificationEmail").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                    // Audit-Felder
                    b.Property<DateTime>("CreateDate").IsRequired().HasColumnType("timestamp without time zone");
                    b.Property<string>("CreatedBy").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime?>("ChangeDate").HasColumnType("timestamp without time zone");
                    b.Property<string>("ChangedBy").HasMaxLength(100).HasColumnType("character varying(100)");
                    // Gültigkeitszeitraum
                    b.Property<DateOnly>("DateFrom").IsRequired().HasColumnType("date");
                    b.Property<DateOnly?>("DateTo").HasColumnType("date");
                    b.HasKey("Id");
                    b.ToTable("Settings");
                });

#pragma warning restore 612, 618
        }
    }
}
